# Funding links shown on your GitHub repository
# Supported platforms: github, patreon, open_collective, ko_fi, tidelift,
#                      community_bridge, liberapay, issuehunt, polar,
#                      buy_me_a_coffee, thanks_dev, custom

github: devhiteshk
# ko_fi: your-ko-fi-username
# patreon: your-patreon-username
# buy_me_a_coffee: your-bmc-username
# custom: https://your-custom-donation-url.com
